### ISSUE TITLE
issue with inputs

### ISSUE THREAD

**Issue by gayanscorpio** [gauravgupta90/Hapi-Mongoose-Angular#1] opened 2016-01-22 11:15 UTC
issue with http://localhost:8080/user.html,

user input does not capture by user.html page , so can you explain how to invoke this project with angular part.

**Comment by gauravgupta90** [comment] 2016-01-23 05:48
Now you can see the user form data, saving to DB.

I will add few more pages to show list of saved user data in enhancement in couple of day.

You can get the latest code from repo.

Closing the issue

**Closed as completed** 2016-01-23 05:48 UTC

**Comment by gayanscorpio** [comment] 2016-01-25 08:44
Hi gauravgupta90,

thanks for update, but still there is an issue with from submission,

so, http://localhost:8080/app/user.html

is this working?

i can pop up page , but, no submission with valid data..
is there any thing, which i missed?

highly appreciate your response..

**Comment by gauravgupta90** [comment] 2016-01-25 10:36
Are you able to see POST request (http://localhost:8080/user)on browser network? 

Also check MongoDb database connection. If not connected to db, you can see connection error on cmd on app startup

Make sure bower components are installed.

Yes the page is working, able to post data successfully.

Sometime the problem is due to browser cache, try reloading page after cleaning brower cache

**Comment by gayanscorpio** [comment] 2016-01-29 16:05
hi gauravgupta90 ,
yes, it works, successfully , thanks a lot :)
